config/routes.rb
Rails.application.routes.draw do
  root 'enquiries#index'
  resources :enquiries, only: [:index, :show, :update] do
    collection do
      get 'load'
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car_listing.rb
class CarListing < ApplicationRecord
  belongs_to :enquiry

  validates :enquiry, presence: true
end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
  include AASM

  belongs_to :source, class_name: 'Website'
  has_one :car_listing, dependent: :destroy

  accepts_nested_attributes_for :car_listing, reject_if: :all_blank
  delegate :make, :model, :colour, :year, :reference, :url, to: :car_listing
  enum status: [:new, :invalid, :done, :expired, :junk], _suffix: true

  scope :new_status_first, -> { order(:status) }
  scope :oldest_first, -> { order(:created_at) }

  aasm column: :status, enum: true do
    state :new, initial: true
    state :invalid, :done, :expired, :junk

    event :invalidate do
      transitions from: :new, to: :invalid
    end

    event :mark_as_done do
      transitions from: :new, to: :done
    end

    event :expire do
      transitions from: :new, to: :expired
    end

    event :mark_as_junk do
      transitions from: [:new, :invalid], to: :junk
    end

    event :reset do
      transitions from: [:invalid, :done, :expired, :junk], to: :new
    end
  end

  def self.search query
    where("lower(name) LIKE :query OR lower(email) LIKE :query", query: "%#{query.downcase}%").distinct
  end
end

app/models/website.rb
class Website < ApplicationRecord
  has_many :enquiries, foreign_key: "source_id"

  validates :name, :domain, presence: true

  def self.amdirect
    find_or_create_by name: 'AMDirect', domain: 'amdirect.test'
  end

  def self.carsforsale
    find_or_create_by name: 'CarsForSale', domain: 'carsforsale.test'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController

  def index
    @enquiries = Enquiry.new_status_first.oldest_first
  end

  def show
    @enquiry = Enquiry.find params[:id]
  end

  def load
    new_enquiries_params = EnquiryParser.call
    Enquiry.create! new_enquiries_params

    if new_enquiries_params.empty?
      redirect_to root_url, flash: { alert: "We couldn't find any new enquiries. <br/> Try running <code>$ rails generate enquiry amdirect</code> or <code>$ rails generate enquiry carsforsale</code> on your terminal first." }
    else
      redirect_to root_url, flash: { notice: "We've found #{new_enquiries_params.size} new enquiries. You can see them listed below." }
    end
  end

  def update
    @enquiry = Enquiry.find params[:id]
    begin @enquiry.update enquiry_params
      redirect_to @enquiry, notice: "The status was successfully updated."
    rescue ArgumentError # enum raises this error on invalid status
      flash.now[:alert] = "We couldn't update the status. Please try again."
      render :show
    end
  end

  def search
    query = params[:query]&.downcase
    if query.blank?
      redirect_to(root_url, flash: { alert: "Please enter a search term." }) and return
    else
      @enquiries = Enquiry.search(params[:query]).new_status_first.oldest_first
      flash.now[:notice] = "Found #{@enquiries.count} results for #{query}"
      render :index
    end
  end

  private
  def enquiry_params
    params.require(:enquiry).permit(:status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
  def options_for_status_select enquiry
    enquiry.aasm.states({:permitted => true}).map {|s| [s.name.to_s.titleize, s.name] }
  end
end

app/views/enquiries/_enquiry.html.erb
<tr class="<%= enquiry.status %>">
  <td>
    <strong><%= link_to enquiry.name, enquiry_path(enquiry) %></strong><br/>
    <%= enquiry.email %>
  </td>
  <td>
    <small>
      Via
      <strong><%= enquiry.source.name %></strong>
      <%= time_ago_in_words enquiry.created_at %>
      ago
      <br/>
      <%= "(#{enquiry.reference})" if enquiry.reference.present? %>
    </small>
  </td>
  <td><code><%= enquiry.status.upcase %></code></td>
  <td>
    <%= link_to "Review", enquiry_path(enquiry) %>
  </td>
</tr>

app/views/enquiries/index.html.erb
<div class="row">
  <div class="five columns">
    <h4>Customer Enquiries</h4>
  </div>
  <div class="four columns">
    <%= link_to 'Check for new enquiries', load_enquiries_path, class: "button button-primary u-pull-left" %>
  </div>
  <div class="three columns">
    <%= form_tag search_enquiries_path, :method => "get" do %>
      <%= search_field_tag :query, params[:query], placeholder: "Search", class: "u-full-width" %>
    <% end %>
  </div>
</div>

<table class="enquiries u-full-width">
  <tbody>
    <%= render @enquiries %>
  </tbody>
</table>

app/views/enquiries/show.html.erb
<div class="enquiry-details">
  <div class="row">
    <div class="column back-link-container">
      <%= link_to "← Back to list", root_path %>
    </div>
  </div>
  <div class="row">
    <div class="column">
      <h4>Enquiry Details</h4>
      <strong>STATUS: <%= @enquiry.status.upcase %></strong>
      <hr/>
    </div>
  </div>
  <div class="row">
    <div class="eight columns">
      <h5>Customer Information</h5>
      <dl>
        <dt>Name:</dt>
        <dd><%= @enquiry.name %></dd>
        <dt>Email:</dt>
        <dd><%= @enquiry.email %></dd>
        <dt>Message:</dt>
        <dd class="message"><%= @enquiry.message %></dd>
      </dl>
    </div>
    <div class="four columns">
      <h5>Vehicle Information</h5>
      <pre>
        <code>
        Make: <%= @enquiry.make %>
        Model: <%= @enquiry.model %>
        Year: <%= @enquiry.year %>
        Colour: <%= @enquiry.colour %>
        </code>
      </pre>
    </div>
  </div>
  <div class="row">
    <div class="enquiry-actions column">
      <hr/>
      <%= form_for @enquiry do |f| %>
        <%= f.label :status, 'Mark as:' %>
        <%= f.select :status, options_for_status_select(@enquiry), include_blank: '—Pick one—' %>
        <%= f.submit "Update Status", class: 'button-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Area Motors</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="column">
          <h2><strong>area</strong>motors</h2>
        </div>
      </div>
      <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg.html_safe, class: "flash #{name}" %>
      <% end -%>
      <%= yield %>
    </div>
  </body>
</html>